language: csharp
mono: none
dotnet: 3.0
before_install:
  # explicitly install other targeted SDKs side by side
  - sudo apt-get install dotnet-sdk-3.1
services:
  - postgresql
script:
  - bash build.sh Test
env:
  - TESTING_IN_TRAVISCI=true
